// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh0cN3XeqVOSaKoBJECMwEGlU5Gv4wmBE',
    appId: '1:678973867730:web:d74b47e3d6f5cedcf40f0b',
    messagingSenderId: '678973867730',
    projectId: 'notes-muhyi',
    authDomain: 'notes-muhyi.firebaseapp.com',
    storageBucket: 'notes-muhyi.appspot.com',
    measurementId: 'G-2HJM65WLZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArjI_OgHFWe2ZDg5Xe-QsnRS0W6pE49tQ',
    appId: '1:678973867730:android:02f51464a5747acdf40f0b',
    messagingSenderId: '678973867730',
    projectId: 'notes-muhyi',
    storageBucket: 'notes-muhyi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaevXcumM6rwxubU9TxzdE9kHZWJ-1m0I',
    appId: '1:678973867730:ios:4fc226c92c8fa6d3f40f0b',
    messagingSenderId: '678973867730',
    projectId: 'notes-muhyi',
    storageBucket: 'notes-muhyi.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaevXcumM6rwxubU9TxzdE9kHZWJ-1m0I',
    appId: '1:678973867730:ios:1a9ab6ac620a2d08f40f0b',
    messagingSenderId: '678973867730',
    projectId: 'notes-muhyi',
    storageBucket: 'notes-muhyi.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}