// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjVHelc_m5EsFPlv9bcdnfrQrtoQlLlaA',
    appId: '1:364801616654:web:8219fbc0b698c60d04455f',
    messagingSenderId: '364801616654',
    projectId: 'firestoremuhyi',
    authDomain: 'firestoremuhyi.firebaseapp.com',
    storageBucket: 'firestoremuhyi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5phu9pMxAxxLS5IDZZc9UKwfeO5XTq2Q',
    appId: '1:364801616654:android:f4e5ce3787bb31a204455f',
    messagingSenderId: '364801616654',
    projectId: 'firestoremuhyi',
    storageBucket: 'firestoremuhyi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHysv5qWdRS4RVLm3cK9F1Dp-tr0bnwRo',
    appId: '1:364801616654:ios:2b6e37a82f852ca004455f',
    messagingSenderId: '364801616654',
    projectId: 'firestoremuhyi',
    storageBucket: 'firestoremuhyi.appspot.com',
    iosBundleId: 'com.example.latFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHysv5qWdRS4RVLm3cK9F1Dp-tr0bnwRo',
    appId: '1:364801616654:ios:a78c1692e7635b5304455f',
    messagingSenderId: '364801616654',
    projectId: 'firestoremuhyi',
    storageBucket: 'firestoremuhyi.appspot.com',
    iosBundleId: 'com.example.latFirestore.RunnerTests',
  );
}
